"""added tracking number and price to Product

Revision ID: c66113566ff3
Revises: 97059c09e526
Create Date: 2025-05-29 01:48:07.190158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66113566ff3'
down_revision: Union[str, None] = '97059c09e526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.drop_column('products', 'tracking_number')
    # ### end Alembic commands ###
